// Code generated by handler_generator. DO NOT EDIT.

package eventsub

import (
	"encoding/json"
	"net/http"

	"github.com/dnsge/twitch-eventsub-framework/v2/bindings"
)

func deserializeAndCallHandler[EventType any](
	h *bindings.NotificationHeaders,
	event json.RawMessage,
	handler EventHandler[EventType],
) error {
	if handler == nil {
		return nil
	}

	var data EventType
	if err := json.Unmarshal(event, &data); err != nil {
		return err
	}

	go handler(h, &data)
	return nil
}

func (h *Handler) handleNotification(w http.ResponseWriter, bodyBytes []byte, headers *bindings.NotificationHeaders) {
	var notification bindings.EventNotification
	if err := json.Unmarshal(bodyBytes, &notification); err != nil {
		http.Error(w, "Invalid JSON body", http.StatusBadRequest)
		return
	}

	var err error
	selector := headers.SubscriptionType + "_" + headers.SubscriptionVersion
	switch selector {
	case "channel.ban_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelBan)

	case "channel.channel_points_custom_reward.add_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelPointsRewardAdd)

	case "channel.channel_points_custom_reward.remove_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelPointsRewardRemove)

	case "channel.channel_points_custom_reward.update_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelPointsRewardUpdate)

	case "channel.channel_points_custom_reward_redemption.add_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelPointsRewardRedemptionAdd)

	case "channel.channel_points_custom_reward_redemption.update_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelPointsRewardRedemptionUpdate)

	case "channel.chat.clear_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelChatClear)

	case "channel.chat.clear_user_messages_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelChatClearUserMessages)

	case "channel.chat.message_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelChatMessage)

	case "channel.chat.message_delete_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelChatMessageDelete)

	case "channel.chat.notification_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelChatNotification)

	case "channel.cheer_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelCheer)

	case "channel.follow_2":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelFollow)

	case "channel.goal.begin_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleGoalBegin)

	case "channel.goal.end_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleGoalEnd)

	case "channel.goal.progress_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleGoalProgress)

	case "channel.hype_train.begin_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleHypeTrainBegin)

	case "channel.hype_train.end_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleHypeTrainEnd)

	case "channel.hype_train.progress_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleHypeTrainProgress)

	case "channel.moderator.add_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelModeratorAdd)

	case "channel.moderator.remove_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelModeratorRemove)

	case "channel.poll.begin_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelPollBegin)

	case "channel.poll.end_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelPollEnd)

	case "channel.poll.progress_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelPollProgress)

	case "channel.prediction.begin_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelPredictionBegin)

	case "channel.prediction.end_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelPredictionEnd)

	case "channel.prediction.lock_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelPredictionLock)

	case "channel.prediction.progress_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelPredictionProgress)

	case "channel.raid_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelRaid)

	case "channel.subscribe_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelSubscribe)

	case "channel.subscription.end_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelSubscriptionEnd)

	case "channel.subscription.gift_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelSubscriptionGift)

	case "channel.subscription.message_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelSubscriptionMessage)

	case "channel.unban_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelUnban)

	case "channel.unban_request.create_beta":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelUnbanRequestCreate)

	case "channel.unban_request.resolve_beta":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelUnbanRequestResolve)

	case "channel.update_2":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleChannelUpdate)

	case "drop.entitlement.grant_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleDropEntitlementGrant)

	case "extension.bits_transaction.create_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleExtensionBitsTransactionCreate)

	case "stream.offline_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleStreamOffline)

	case "stream.online_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleStreamOnline)

	case "user.authorization.grant_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleUserAuthorizationGrant)

	case "user.authorization.revoke_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleUserAuthorizationRevoke)

	case "user.update_1":
		err = deserializeAndCallHandler(headers, notification.Event, h.HandleUserUpdate)

	default:
		http.Error(w, "Unsupported notification type and version", http.StatusBadRequest)
		return
	}

	if err != nil {
		http.Error(w, "Invalid notification", http.StatusBadRequest)
		return
	}

	writeEmptyOK(w)
}
